apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tester-app
  name: tester-app-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30003
  selector:
    app: tester-app
  type: NodePort
status:
  loadBalancer: {}