apiVersion: v1
kind: Service
metadata:
  name: manager-service
  labels:
    name: manager-service
spec:
  type: NodePort
  ports:
    - port: 8899
      nodePort: 30365
      protocol: TCP
  selector:
    app: manager-app