apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bz-app
  name: bz-app-service
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30002
  selector:
    app: bz-app
  type: NodePort
status:
  loadBalancer: {}